import { expect, test } from '@playwright/test'

test.use({ extraHTTPHeaders: { 'X-Dev-User': 'none' } })

test('admin이 실제 로그인한 뒤 복원한 화면 구성과 문서 흐름을 확인한다', async ({ page }) => {
  test.skip(!process.env.E2E_USER || !process.env.E2E_PASSWORD, 'E2E_USER와 E2E_PASSWORD가 설정되지 않았습니다.')

  await page.goto('/auth/sign-in')
  await page.getByLabel('ID').fill(process.env.E2E_USER!)
  await page.getByLabel('Password').fill(process.env.E2E_PASSWORD!)
  await page.getByRole('button', { name: 'Sign In' }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('heading', { name: /안녕하세요,/ })).toBeVisible()
  await page.getByRole('link', { name: '매뉴얼 목록 열기' }).click()
  await expect(page.getByRole('heading', { name: 'Manuals' })).toBeVisible()
  await page.getByRole('button', { name: 'New Manual' }).click()
  await expect(page.getByRole('dialog', { name: 'New System Manual' })).toBeVisible()
  const newDialog = page.getByRole('dialog', { name: 'New System Manual' })
  await expect(newDialog.getByRole('textbox', { name: 'Model Name' })).toBeVisible()
  await expect(newDialog.getByPlaceholder('Job Number 검색 (datasheet)')).toBeVisible()
  await expect(newDialog.locator('select').nth(0)).toBeVisible() // Label
  await expect(newDialog.locator('select').nth(1)).toBeVisible() // Cooling
  await expect(newDialog.getByRole('textbox', { name: 'Option' })).toBeVisible()
  await expect(newDialog.getByRole('textbox', { name: 'Version' })).toBeVisible()
  await expect(newDialog.getByRole('combobox', { name: 'Page Size' })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: '취소' }).click()

  // 병렬 쓰기 API 검증이 만드는 E2E 임시 문서는 finally에서 삭제되므로, 기존 문서를 순회한다.
  const manualRows = page.locator('tbody tr.clickable-row')
  await expect(manualRows.first()).toBeVisible()
  await manualRows.first().click()
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: '목차관리' })).toBeVisible()
  await page.getByRole('link', { name: '미리보기 · PDF' }).click()
  await expect(page.getByRole('navigation', { name: '미리보기 도구' })).toBeVisible()
  await expect(page.frameLocator('iframe[title="문서 미리보기"]').locator('#docSheet')).toBeVisible()
  await expect(page.getByRole('link', { name: '문서 정보' })).toBeVisible()
  await expect(page.getByRole('button', { name: '인쇄' })).toBeVisible()
  await expect(page.getByRole('button', { name: '페이지 보기' })).toBeVisible()
  await page.getByRole('link', { name: '← 편집기' }).click()
  await expect(page.locator('.manual-editor')).toBeVisible()
  await expect(page.getByRole('button', { name: '목차관리' })).toBeVisible()
  await expect(page.locator('.manual-outline')).toBeVisible()

  await page.goto('/admin/user')
  await expect(page.getByRole('heading', { name: 'Users' })).toBeVisible()
  await expect(page.locator('thead')).toContainText('이름')
  await expect(page.locator('thead')).toContainText('이메일')
  await page.getByRole('button', { name: '사용자 등록' }).click()
  const userDialog = page.getByRole('dialog', { name: '사용자 등록' })
  await expect(userDialog.getByPlaceholder('영문·숫자 4~20자')).toBeVisible()
  await expect(userDialog.getByText('8자 이상, 영문·숫자·특수문자를 각각 1자 이상 포함해야 합니다.')).toBeVisible()
  await userDialog.getByRole('button', { name: '취소' }).click()

  await page.goto('/admin/code')
  await expect(page.getByRole('button', { name: '코드 추가' })).toBeVisible()
  await page.getByRole('button', { name: '코드 추가' }).click()
  const codeDialog = page.getByRole('dialog', { name: '코드 추가' })
  await expect(codeDialog.getByPlaceholder('COVER')).toBeVisible()
  await expect(codeDialog.getByPlaceholder('TITLE_LINE1')).toBeVisible()
  await expect(codeDialog.getByLabel('정렬 순서')).toHaveValue('0')
  await codeDialog.getByRole('button', { name: '취소' }).click()

  await page.goto('/admin/section-template')
  await expect(page.getByRole('button', { name: '목차 추가' })).toBeVisible()
  await page.getByRole('button', { name: '목차 추가' }).click()
  const templateDialog = page.getByRole('dialog', { name: '목차 추가' })
  await expect(templateDialog.getByText('기본 내용')).toBeVisible()
  await expect(templateDialog.locator('.ck-editor__editable_inline')).toBeVisible()
  await templateDialog.getByRole('button', { name: '취소' }).click()

  await page.goto('/admin/setting')
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'SMTP' })).toBeVisible()
})
