<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api, query } from '../api/client'
import BlockEditor from '../features/editor/BlockEditor.vue'
import type { ManualHeader, ManualSection } from '../api/types'
interface Block { ELE_ID?: number; M_ID: string; SEC_ID: number; ELE_TYPE: 'TEXT' | 'IMAGE' | 'TABLE'; ORDER_NUM: number; WIDTH: number; HEIGHT: number; CONTENT_HTML?: string; IMAGE_PATH?: string; CAPTION?: string; STYLE_JSON?: string; ROW_VER?: string }
interface Access { CAN_EDIT: string }
const route = useRoute(); const mid = computed(() => typeof route.query.mid === 'string' ? route.query.mid : '')
const header = ref<ManualHeader | null>(null); const sections = ref<ManualSection[]>([]); const blocks = ref<Block[]>([]); const access = ref<Access | null>(null); const activeSecId = ref<number | null>(null); const error = ref(''); const saving = ref<number | 'new' | null>(null)
const activeSection = computed(() => sections.value.find(section => section.SEC_ID === activeSecId.value) ?? null)
const activeBlocks = computed(() => blocks.value.filter(block => block.SEC_ID === activeSecId.value).sort((left, right) => left.ORDER_NUM - right.ORDER_NUM))
const canEdit = computed(() => access.value?.CAN_EDIT === 'Y' && activeSection.value?.CAN_EDIT_SEC === 'Y')
async function load() { if (!mid.value) return; error.value = ''; try { const data = await api<{ header: ManualHeader; sections: ManualSection[]; blocks: Block[]; access: Access }>(query('/api/editor/data', { mid: mid.value })); header.value = data.header; sections.value = data.sections; blocks.value = data.blocks; access.value = data.access; activeSecId.value ??= data.sections.find(section => section.SEC_TYPE !== 'PAGEBREAK')?.SEC_ID ?? null } catch (e) { error.value = e instanceof Error ? e.message : '편집기를 불러오지 못했습니다.' } }
async function save(block: Block) { if (!canEdit.value) return; saving.value = block.ELE_ID ?? 'new'; try { const result = await api<{ block: Block }>('/api/editor/block', { method: 'POST', body: JSON.stringify(block) }); const index = blocks.value.findIndex(item => item.ELE_ID === block.ELE_ID); if (index >= 0) blocks.value[index] = result.block; else blocks.value.push(result.block) } catch (e) { error.value = e instanceof Error ? e.message : '블록을 저장하지 못했습니다.' } finally { saving.value = null } }
function addText() { if (!activeSecId.value || !canEdit.value) return; blocks.value.push({ M_ID: mid.value, SEC_ID: activeSecId.value, ELE_TYPE: 'TEXT', ORDER_NUM: activeBlocks.value.length + 1, WIDTH: 0, HEIGHT: 0, CONTENT_HTML: '' }) }
async function remove(block: Block) { if (!block.ELE_ID || !confirm('이 블록을 삭제합니다.')) return; try { await api(query('/api/editor/block', { eleId: block.ELE_ID, mid: mid.value }), { method: 'DELETE' }); blocks.value = blocks.value.filter(item => item.ELE_ID !== block.ELE_ID) } catch (e) { error.value = e instanceof Error ? e.message : '블록을 삭제하지 못했습니다.' } }
onMounted(load)
</script>
<template><section><div class="page-title"><div><h1>문서 편집기</h1><p>{{ header?.MODEL_NAME }}</p></div><RouterLink class="button secondary" :to="{ path: '/manual/preview', query: { mid } }">미리보기</RouterLink></div><p v-if="error" class="error">{{ error }}</p><p v-else-if="!header">불러오는 중…</p><div v-else class="editor-grid"><aside><h2>목차</h2><button v-for="section in sections.filter(item => item.SEC_TYPE !== 'PAGEBREAK')" :key="section.SEC_ID" class="section-button" :class="{ selected: section.SEC_ID === activeSecId }" :style="{ marginLeft: `${(section.SEC_LEVEL - 1) * .75}rem` }" @click="activeSecId = section.SEC_ID">{{ section.SEC_NO }} {{ section.TITLE }}</button></aside><div><div class="editor-heading"><div><h2>{{ activeSection?.TITLE }}</h2><p v-if="!canEdit">이 목차는 현재 사용자에게 편집 권한이 없습니다.</p></div><button :disabled="!canEdit" @click="addText">텍스트 블록 추가</button></div><article v-for="(block, index) in activeBlocks" :key="block.ELE_ID ?? `new-${index}`" class="block-card"><BlockEditor v-if="block.ELE_TYPE === 'TEXT'" :model-value="block.CONTENT_HTML ?? ''" :read-only="!canEdit" :upload-url="`/api/editor/image?mid=${encodeURIComponent(mid)}`" @update:model-value="block.CONTENT_HTML = $event" @blur="save(block)" /><p v-else>이 블록 유형은 전환 중입니다: {{ block.ELE_TYPE }}</p><footer><span>{{ saving === (block.ELE_ID ?? 'new') ? '저장 중…' : '' }}</span><button class="inline" :disabled="!canEdit" @click="save(block)">저장</button><button class="inline danger" :disabled="!canEdit || !block.ELE_ID" @click="remove(block)">삭제</button></footer></article><p v-if="activeBlocks.length === 0" class="empty">블록이 없습니다.</p></div></div></section></template>
