<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, query } from '../api/client'
interface Setting { SYSTEM_NAME: string; SYSTEM_EMAIL: string; SYSTEM_SMTP: string; SYSTEM_SMTP_PORT: string; SYSTEM_SMTP_SECURE: string; SYSTEM_EMAIL_ID: string; SYSTEM_SMTP_SCOPE: string }
interface Log { SEND_DT?: string; TO_EMAIL?: string; SUBJECT?: string; RESULT?: string }
const setting = ref<Setting>({ SYSTEM_NAME: '', SYSTEM_EMAIL: '', SYSTEM_SMTP: '', SYSTEM_SMTP_PORT: '587', SYSTEM_SMTP_SECURE: 'STARTTLS', SYSTEM_EMAIL_ID: '', SYSTEM_SMTP_SCOPE: 'T' }); const password = ref(''); const hasPassword = ref(false); const testTo = ref(''); const logs = ref<Log[]>([]); const error = ref(''); const saving = ref(false); const sending = ref(false)
const testMode = computed(() => setting.value.SYSTEM_SMTP_SCOPE === 'T')
async function load() { try { const data = await api<{ setting: Setting; hasPassword: boolean }>('/api/admin/setting/mail'); setting.value = data.setting; hasPassword.value = data.hasPassword } catch (e) { error.value = e instanceof Error ? e.message : '설정을 불러오지 못했습니다.' } }
async function loadLogs() { try { logs.value = (await api<{ list: Log[] }>('/api/admin/setting/mail/log')).list } catch (e) { error.value = e instanceof Error ? e.message : '발송 이력을 불러오지 못했습니다.' } }
async function save() { saving.value = true; try { await api('/api/admin/setting/mail', { method: 'POST', body: JSON.stringify({ ...setting.value, SYSTEM_EMAIL_PASSWORD: password.value }) }); password.value = ''; await load() } catch (e) { error.value = e instanceof Error ? e.message : '설정을 저장하지 못했습니다.' } finally { saving.value = false } }
async function sendTest() { if (!testTo.value) { error.value = '받는 사람 주소를 입력하세요.'; return }; sending.value = true; try { await api(query('/api/admin/setting/mail/test', { to: testTo.value }), { method: 'POST' }); await loadLogs() } catch (e) { error.value = e instanceof Error ? e.message : '테스트 메일을 보내지 못했습니다.' } finally { sending.value = false } }
onMounted(async () => { await Promise.all([load(), loadLogs()]) })
</script>
<template><section><div class="page-title"><div><h1>메일 설정</h1><p>SMTP 발송 환경을 설정합니다.</p></div></div><p v-if="error" class="error">{{ error }}</p><div class="admin-grid"><form class="panel" @submit.prevent="save"><label>시스템 이름<input v-model="setting.SYSTEM_NAME" required /></label><label>발신 주소<input v-model="setting.SYSTEM_EMAIL" type="email" required /></label><label>SMTP 서버<input v-model="setting.SYSTEM_SMTP" required /></label><label>포트<input v-model="setting.SYSTEM_SMTP_PORT" type="number" required /></label><label>보안<select v-model="setting.SYSTEM_SMTP_SECURE"><option>STARTTLS</option><option>SSL</option><option>NONE</option></select></label><label>계정<input v-model="setting.SYSTEM_EMAIL_ID" /></label><label>비밀번호 <small>{{ hasPassword ? '설정됨 — 비워 두면 유지' : '미설정' }}</small><input v-model="password" type="password" /></label><label>발송 범위<select v-model="setting.SYSTEM_SMTP_SCOPE"><option value="T">TEST (메일 파일 저장)</option><option value="P">PRODUCTION</option></select></label><button :disabled="saving">{{ saving ? '저장 중…' : '저장' }}</button></form><div class="panel"><h2>테스트 발송</h2><p>{{ testMode ? 'TEST 모드에서는 App_Data/mail-drop에 저장됩니다.' : '실제 메일을 발송합니다.' }}</p><label>받는 사람<input v-model="testTo" type="email" /></label><button :disabled="sending" @click="sendTest">{{ sending ? '발송 중…' : '테스트 메일 발송' }}</button><h2>최근 발송 이력</h2><table><thead><tr><th>수신자</th><th>제목</th><th>결과</th></tr></thead><tbody><tr v-for="(log, index) in logs" :key="index"><td>{{ log.TO_EMAIL }}</td><td>{{ log.SUBJECT }}</td><td>{{ log.RESULT }}</td></tr></tbody></table></div></div></section></template>
