<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, query } from '../api/client'
import type { ManualHeader, ManualSection } from '../api/types'
const route = useRoute(); const router = useRouter(); const mid = computed(() => typeof route.query.mid === 'string' ? route.query.mid : '')
const header = ref<ManualHeader | null>(null); const sections = ref<ManualSection[]>([]); const form = ref<Record<string, unknown> | null>(null); const canEdit = ref(false); const error = ref(''); const loading = ref(false); const saving = ref(false)
async function load() { if (!mid.value) return; loading.value = true; try { const data = await api<{ header: ManualHeader; sections: ManualSection[]; access: { CAN_EDIT: string } }>(query('/api/manual/find', { mid: mid.value })); header.value = data.header; sections.value = data.sections; form.value = { ...data.header }; canEdit.value = data.access.CAN_EDIT === 'Y' } catch (e) { error.value = e instanceof Error ? e.message : '문서를 불러오지 못했습니다.' } finally { loading.value = false } }
async function create() { try { const data = await api<{ M_ID: string }>('/api/manual/create', { method: 'POST', body: JSON.stringify({ MODEL_NAME: '새 문서', PAGE_SIZE: 'LETTER' }) }); await router.replace({ path: '/manual/detail', query: { mid: data.M_ID } }); await load() } catch (e) { error.value = e instanceof Error ? e.message : '문서를 만들지 못했습니다.' } }
async function save() { if (!form.value) return; saving.value = true; try { await api('/api/manual/header', { method: 'POST', body: JSON.stringify({ ...form.value, M_ID: mid.value }) }); await load() } catch (e) { error.value = e instanceof Error ? e.message : '문서를 저장하지 못했습니다.' } finally { saving.value = false } }
async function remove() { if (!confirm('이 문서를 삭제합니다.')) return; try { await api(query('/api/manual/delete', { mid: mid.value }), { method: 'DELETE' }); await router.push('/manual') } catch (e) { error.value = e instanceof Error ? e.message : '문서를 삭제하지 못했습니다.' } }
onMounted(load)
</script>
<template><section><div class="page-title"><div><h1>{{ header?.MODEL_NAME ?? '새 문서' }}</h1><p v-if="header">{{ header.DOC_NUM }} · Rev {{ header.REVISION }} · {{ header.STATUS }}</p></div><div class="actions" v-if="mid"><RouterLink class="button secondary" :to="{ path: '/manual/preview', query: { mid } }">미리보기</RouterLink><RouterLink class="button" :to="{ path: '/editor', query: { mid } }">편집기</RouterLink></div></div><p v-if="error" class="error">{{ error }}</p><div v-else-if="!mid" class="empty"><p>새 문서를 생성합니다.</p><button @click="create">문서 생성</button></div><div v-else-if="loading">불러오는 중…</div><template v-else-if="header && form"><form class="panel detail-form" @submit.prevent="save"><label>Model Name<input v-model="form.MODEL_NAME" :readonly="!canEdit" required /></label><label>Job Number<input v-model="form.JOB_NUMBER" :readonly="!canEdit" /></label><label>Label<select v-model="form.LABEL" :disabled="!canEdit"><option value="">없음</option><option value="EXODUS">Exodus</option><option value="OEM">OEM</option></select></label><label>Cooling<select v-model="form.COOLING" :disabled="!canEdit"><option value="">없음</option><option value="AIR">Air</option><option value="LIQUID">Liquid</option></select></label><label>Page Size<select v-model="form.PAGE_SIZE" :disabled="!canEdit"><option value="LETTER">Letter</option><option value="A4">A4</option></select></label><label>Option<input v-model="form.OPTION_TEXT" :readonly="!canEdit" /></label><div v-if="canEdit"><button :disabled="saving">{{ saving ? '저장 중…' : '저장' }}</button><button class="danger" type="button" @click="remove">삭제</button></div></form><h2>목차</h2><ol class="sections"><li v-for="section in sections" :key="section.SEC_ID" :style="{ marginLeft: `${(section.SEC_LEVEL - 1) * 1.5}rem` }">{{ section.SEC_NO }} {{ section.TITLE }} <small>{{ section.ASSIGNED_TEAM }}</small></li></ol></template></section></template>
