<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, query } from '../api/client'
import BlockEditor from '../features/editor/BlockEditor.vue'

interface Template { TPL_ID: number; LABEL?: string; COOLING?: string; SEC_LEVEL: number; SEC_NO?: string; TITLE: string; IS_MANDATORY: string; ORDER_NUM: number; ASSIGNED_TEAM?: string; CONTENT_HTML?: string; TITLE_ALIGN: string; SEC_TYPE: string; SHOW_IN_TOC: string; TITLE_UNDERLINE: string }
type TemplateInput = Omit<Template, 'TPL_ID'> & { TPL_ID?: number }
const list = ref<Template[]>([]); const label = ref(''); const cooling = ref(''); const form = ref<TemplateInput | null>(null); const error = ref(''); const saving = ref(false)
const normalTemplates = computed(() => list.value.filter(item => item.SEC_TYPE !== 'PAGEBREAK'))
async function load() { try { list.value = (await api<{ list: Template[] }>(query('/api/admin/section-template/list', { label: label.value, cooling: cooling.value }))).list } catch (e) { error.value = e instanceof Error ? e.message : '목차 템플릿을 불러오지 못했습니다.' } }
function open(item?: Template) { error.value = ''; form.value = item ? { ...item } : { LABEL: label.value, COOLING: cooling.value, SEC_LEVEL: 1, SEC_NO: '', TITLE: '', IS_MANDATORY: 'Y', ORDER_NUM: list.value.length + 1, ASSIGNED_TEAM: '', CONTENT_HTML: '', TITLE_ALIGN: 'LEFT', SEC_TYPE: 'NORMAL', SHOW_IN_TOC: 'Y', TITLE_UNDERLINE: 'N' } }
async function save() { if (!form.value) return; if (form.value.SEC_TYPE === 'PAGEBREAK') form.value.TITLE = '페이지 나눔'; saving.value = true; try { await api('/api/admin/section-template', { method: 'POST', body: JSON.stringify(form.value) }); form.value = null; await load() } catch (e) { error.value = e instanceof Error ? e.message : '템플릿을 저장하지 못했습니다.' } finally { saving.value = false } }
async function remove(item: Template) { if (!confirm(`“${item.TITLE}” 항목을 삭제합니다.`)) return; try { await api(query('/api/admin/section-template', { tplId: item.TPL_ID }), { method: 'DELETE' }); await load() } catch (e) { error.value = e instanceof Error ? e.message : '템플릿을 삭제하지 못했습니다.' } }
async function move(index: number, direction: number) { const target = index + direction; if (target < 0 || target >= list.value.length) return; const reordered = [...list.value]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; list.value = reordered; const orders = reordered.map((item, order) => `${item.TPL_ID}:${order + 1}`).join(','); try { await api(query('/api/admin/section-template/order', { orders }), { method: 'POST' }) } catch (e) { error.value = e instanceof Error ? e.message : '순서를 저장하지 못했습니다.'; await load() } }
onMounted(load)
</script>
<template><section><div class="page-title"><div><h1>목차 템플릿</h1><p>Label·Cooling 조합별 기본 목차를 관리합니다.</p></div><button @click="open()">템플릿 추가</button></div><p v-if="error" class="error">{{ error }}</p><div class="toolbar"><label>Label<select v-model="label" @change="load"><option value="">전체</option><option value="EXODUS">Exodus</option><option value="OEM">OEM</option></select></label><label>Cooling<select v-model="cooling" @change="load"><option value="">전체</option><option value="AIR">Air</option><option value="LIQUID">Liquid</option></select></label></div><div class="admin-grid"><table><thead><tr><th>순서</th><th>범위</th><th>제목</th><th>담당 팀</th><th></th></tr></thead><tbody><tr v-for="(item, index) in list" :key="item.TPL_ID"><td>{{ index + 1 }}</td><td>{{ item.LABEL || '전체' }} · {{ item.COOLING || '전체' }}</td><td>{{ item.SEC_TYPE === 'PAGEBREAK' ? '페이지 나눔' : `${item.SEC_NO || ''} ${item.TITLE}` }}</td><td>{{ item.ASSIGNED_TEAM }}</td><td><button class="inline" @click="move(index, -1)">↑</button><button class="inline" @click="move(index, 1)">↓</button><button class="inline" @click="open(item)">수정</button><button class="inline danger" @click="remove(item)">삭제</button></td></tr></tbody></table><form v-if="form" class="panel template-form" @submit.prevent="save"><h2>{{ form.TPL_ID ? '템플릿 수정' : '템플릿 추가' }}</h2><label>종류<select v-model="form.SEC_TYPE"><option value="NORMAL">일반 목차</option><option value="PAGEBREAK">페이지 나눔</option></select></label><template v-if="form.SEC_TYPE !== 'PAGEBREAK'"><label>Label<select v-model="form.LABEL"><option value="">전체</option><option value="EXODUS">Exodus</option><option value="OEM">OEM</option></select></label><label>Cooling<select v-model="form.COOLING"><option value="">전체</option><option value="AIR">Air</option><option value="LIQUID">Liquid</option></select></label><label>단계<select v-model.number="form.SEC_LEVEL"><option :value="1">대제목</option><option :value="2">중제목</option><option :value="3">소제목</option></select></label><label>번호<input v-model="form.SEC_NO" /></label><label>제목<input v-model="form.TITLE" required /></label><label>담당 팀<input v-model="form.ASSIGNED_TEAM" /></label><label>정렬<select v-model="form.TITLE_ALIGN"><option value="LEFT">왼쪽</option><option value="CENTER">가운데</option><option value="RIGHT">오른쪽</option></select></label><BlockEditor :model-value="form.CONTENT_HTML ?? ''" upload-url="/api/admin/section-template/image" @update:model-value="form.CONTENT_HTML = $event" /></template><button :disabled="saving">{{ saving ? '저장 중…' : '저장' }}</button><button class="secondary" type="button" @click="form = null">취소</button></form></div></section></template>
